
server:
  port: 80
  servlet:
      jsp:
        registered: false
  error:
    whitelabel: 
      enabled: false

spring:
  application:
    name: sprintplanner
  banner:
    location: classpath:banner.txt
  profiles:
    active: prod
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/sprintplanner?createDatabaseIfNotExist=false&useSSL=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
#    username:
#    password:
  h2:
    console:
      settings:
        trace: false
        web-allow-others: false
  datasource:
    url: jdbc:h2:./data/sprintplanner;DB_CLOSE_ON_EXIT=false;DATABASE_TO_UPPER=false;SCHEMA=sprintplanner
    driverClassName: org.h2.Driver
    username: 
    password: 
  jpa:
    open-in-view: false
    show-sql: false
    generate-ddl: true
    hibernate:
       ddl-auto: update
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
        jdbc:
          batch_size: 10
        order_inserts: false
        order_updates: false
        generate_statistics: false
  messages:
    use-code-as-default-message: false
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
  resources:
    add-mappings: true

logging:
  config: classpath:logback-spring.xml
  
cron:
  config:
    handle-release: "* * * * 1 *"
    handle-support: "* * * * 1 *"
    
jwt-auth-server:
  keyStore: jwt.jks
  keyPass: 123456
  keyAlias: jwt
  accessTokenValiditySeconds: 1800
  refreshTokenValiditySeconds: 86400
      