
server:
  port: 8081
  servlet:
      context-path: /
      jsp:
        registered: false
  error:
    whitelabel: 
      enabled: false

spring:
  application:
    name: sprintplanner
  banner:
    location: classpath:banner-dev.txt
  profiles:
    active: h2-dev
  datasource:
    url: jdbc:h2:./data/sprintplanner;DB_CLOSE_ON_EXIT=false;DATABASE_TO_UPPER=false;SCHEMA=sprintplanner
    driverClassName: org.h2.Driver
    username: root
    password: root
  h2:
    console:
      settings:
        trace: false
        web-allow-others: false
  jpa: 
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
       ddl-auto: none
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        jdbc:
          batch_size: 10
        order_inserts: false
        order_updates: false
        generate_statistics: true
  messages:
    use-code-as-default-message: false
  mvc:
    throw-exception-if-no-handler-found: true
    favicon:
      enabled: false
  resources:
    add-mappings: true
  mail:
    default-encoding: UTF-8
    host: 
    port: 2525
    protocol: smtp

logging:
  config: classpath:logback-spring-dev.xml
    
cron:
  config:
    handle-release: "5 0 */6 * * *"
    handle-support: "6 0 */6 * * *"
    send-releaser-mail: "8 0 */6 * * *"
    send-support-mail: "10 0 */6 * * *"
    
config:
  external-apis:
    urls: 
      github: "https://api.github.com/repos/"
      jira: "http://localhost:9999/jira/ticket/"
    
    
jwt-auth-server:
  keyStore: jwt.jks
  keyPass: 123456
  keyAlias: jwt
  accessTokenValiditySeconds: 86400
  refreshTokenValiditySeconds: 86400
    
    